# Generated by Django 4.0 on 2021-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_character_episode_quote_delete_makale_episode_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
