# Generated by Django 4.0 on 2021-12-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_remove_character_quotes_remove_quote_character_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='quotes',
        ),
    ]
