# Generated by Django 4.0 on 2021-12-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_remove_quote_episode_name_delete_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='video',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
