# Generated by Django 4.0 on 2021-12-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_quote_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
