# Generated by Django 4.0 on 2021-12-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='most_used_word',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='series.character'),
        ),
    ]
