# Generated by Django 4.0 on 2021-12-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0010_character_most_used_word_alter_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
